"""little bit fixed chat model

Revision ID: 8b4372abf6c3
Revises: 1fb6b06d9fa5
Create Date: 2024-06-01 11:46:44.461789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4372abf6c3'
down_revision = '1fb6b06d9fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
