"""default[] for User

Revision ID: b8ec1c060dff
Revises: 8b4372abf6c3
Create Date: 2024-06-02 16:22:25.491671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ec1c060dff'
down_revision = '8b4372abf6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
