"""time for msg

Revision ID: bcb282ce2c7a
Revises: 870661b8e612
Create Date: 2024-06-02 17:25:57.733295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb282ce2c7a'
down_revision = '870661b8e612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
