"""time+tz+date+time for msg

Revision ID: cb532dbfb515
Revises: 5cad223afc0f
Create Date: 2024-06-02 20:54:47.508923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb532dbfb515'
down_revision = '5cad223afc0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('message', sa.Column('timezone', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'timezone')
    op.drop_column('message', 'date')
    # ### end Alembic commands ###
