"""nullabel true for userid in msg

Revision ID: 870661b8e612
Revises: b8ec1c060dff
Create Date: 2024-06-02 17:07:50.342231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870661b8e612'
down_revision = 'b8ec1c060dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
