"""fixed default role_id

Revision ID: 0429ce4a926e
Revises: 978386698c77
Create Date: 2024-05-16 01:22:15.142794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0429ce4a926e'
down_revision = '978386698c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
