"""association table

Revision ID: 17d3e1aa246d
Revises: 9b1c67b55fe3
Create Date: 2024-06-06 13:56:36.709346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d3e1aa246d'
down_revision = '9b1c67b55fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
