"""association table chat_user

Revision ID: 685585c37d24
Revises: 17d3e1aa246d
Create Date: 2024-06-06 14:09:51.386961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685585c37d24'
down_revision = '17d3e1aa246d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
