"""add username to message

Revision ID: 0e340e652c56
Revises: d8e7a7adc073
Create Date: 2024-05-30 14:11:34.692982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e340e652c56'
down_revision = 'd8e7a7adc073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
