"""added chat&messages

Revision ID: d8e7a7adc073
Revises: 0429ce4a926e
Create Date: 2024-05-18 21:43:53.134214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e7a7adc073'
down_revision = '0429ce4a926e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chats', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chats')
    # ### end Alembic commands ###
