"""association table chat_user

Revision ID: 183c6cb002d6
Revises: 685585c37d24
Create Date: 2024-06-06 14:25:41.092127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183c6cb002d6'
down_revision = '685585c37d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
