"""fix_of_init

Revision ID: 86d2c787c47b
Revises: e74689555b1b
Create Date: 2024-06-25 14:13:06.556863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d2c787c47b'
down_revision = 'e74689555b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
