"""default timezone

Revision ID: d9026d92c241
Revises: 489b8fbc7d44
Create Date: 2024-06-27 17:20:54.814822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9026d92c241'
down_revision = '489b8fbc7d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
