"""add username to message 2

Revision ID: 28ab4bd404ee
Revises: 6ff5f6ff6b0a
Create Date: 2024-05-30 19:39:19.854321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ab4bd404ee'
down_revision = '6ff5f6ff6b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
