"""add username to message

Revision ID: bd5a338caabb
Revises: 0e340e652c56
Create Date: 2024-05-30 19:32:10.548853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5a338caabb'
down_revision = '0e340e652c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
