"""time for messages

Revision ID: 4bdadfc407df
Revises: da2bd2536ce0
Create Date: 2024-05-31 11:58:01.032512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bdadfc407df'
down_revision = 'da2bd2536ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'time')
    # ### end Alembic commands ###
