"""msg id for chat

Revision ID: 671012aff9d5
Revises: 4bdadfc407df
Create Date: 2024-05-31 18:35:23.130092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671012aff9d5'
down_revision = '4bdadfc407df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('last_msg_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat', 'message', ['last_msg_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_column('chat', 'last_msg_id')
    # ### end Alembic commands ###
