"""users for chat

Revision ID: 1fb6b06d9fa5
Revises: 671012aff9d5
Create Date: 2024-05-31 19:39:09.873133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb6b06d9fa5'
down_revision = '671012aff9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('users', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'users')
    # ### end Alembic commands ###
