"""wwww

Revision ID: 5c441a4bdb3f
Revises: ceddc4d92e1a
Create Date: 2024-05-15 15:52:16.990012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c441a4bdb3f'
down_revision = 'ceddc4d92e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('www',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_www_id'), 'www', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_www_id'), table_name='www')
    op.drop_table('www')
    # ### end Alembic commands ###
