"""add username to message

Revision ID: 6ff5f6ff6b0a
Revises: bd5a338caabb
Create Date: 2024-05-30 19:34:47.808165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff5f6ff6b0a'
down_revision = 'bd5a338caabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
