"""msg and chats

Revision ID: 92e609c48ae8
Revises: f671e58a4b33
Create Date: 2024-05-30 21:06:37.230907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e609c48ae8'
down_revision = 'f671e58a4b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
