"""ability

Revision ID: 978386698c77
Revises: 5c441a4bdb3f
Create Date: 2024-05-15 17:24:24.635133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978386698c77'
down_revision = '5c441a4bdb3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ability_id'), 'ability', ['id'], unique=False)
    op.drop_index('ix_www_id', table_name='www')
    op.drop_table('www')
    op.add_column('role', sa.Column('role_ability_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'role', 'ability', ['role_ability_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'role_ability_id')
    op.create_table('www',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='www_pkey')
    )
    op.create_index('ix_www_id', 'www', ['id'], unique=False)
    op.drop_index(op.f('ix_ability_id'), table_name='ability')
    op.drop_table('ability')
    # ### end Alembic commands ###
