"""msg and chats

Revision ID: f671e58a4b33
Revises: 28ab4bd404ee
Create Date: 2024-05-30 20:40:12.320795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f671e58a4b33'
down_revision = '28ab4bd404ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
